// /vitest.workers.config.ts
// Drives @cloudflare/vitest-pool-workers — these tests boot the actual
// Worker entry point inside workerd / miniflare, so DO storage, alarms,
// and WebSocket Hibernation behave like production.
//
// Vitest 4 API: `cloudflareTest` is a Vite plugin, not a pool option.
// Slower than vitest.config.ts so kept opt-in via `npm run test:workers`. // L3_架構含防禦觀測

import { defineConfig } from "vitest/config";
import { cloudflareTest } from "@cloudflare/vitest-pool-workers";

export default defineConfig({
  plugins: [
    cloudflareTest({
      singleWorker: true,
      miniflare: {
        // Test fixtures — these never reach production. The ES256
        // private JWK is a known-good test key (NOT used for signing
        // anything outside the test isolate).
        bindings: {
          // Real EC P-256 JWK generated by scripts/gen-jwk.mjs. Test-only.
          JWT_PRIVATE_JWK: JSON.stringify({
            kty: "EC", crv: "P-256",
            x: "en4UoqeDNiWEYpfAwHYq8ORxSy102KlSWVNH1rof0RY",
            y: "vERZhoAVXOcrb-bpkvB_etr8_35E1zl4VeizEcCn9jk",
            d: "2bsnwATQP8qaf3YyyUEk4bScmtewqeqBfhfvpEOAPPI",
            kid: "7c739aba-da2a-497f-86c6-67350ffe5cae",
            alg: "ES256", use: "sig",
          }),
          ADMIN_SECRET: "test-admin",
        },
      },
      wrangler: { configPath: "./wrangler.toml" },
    }),
  ],
  test: {
    include: ["test/workers/**/*.test.ts"],
  },
});
