-- /src/db/schema.sql
-- DEPRECATED single-file bootstrap. Kept as a marker so old references and
-- runbooks don't 404, but the live schema is now driven by:
--
--     migrations/0001_initial.sql   <- baseline (matches what this file used to be)
--     migrations/000N_*.sql         <- every subsequent delta
--
-- Apply via `npm run db:migrate:local` (dev) or `npm run db:migrate:prod` (prod).
-- See migrations/README.md for the workflow.
--
-- DO NOT execute this file directly against any D1 instance. It is intentionally
-- empty so a fat-fingered `wrangler d1 execute --file src/db/schema.sql` is
-- harmless rather than racing the migrations tracker.
